# Generated by Django 5.2.4 on 2025-10-27 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('elektronika', 'Elektronika'), ('uy_jihozlari', 'Uy jihozlari'), ('kiyim', 'Kiyim-kechak'), ('avto', 'Avto ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya')),
                ('mahsulotturi', models.CharField(max_length=100, verbose_name='Mahsulot turi')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('fargona', 'Farg‘ona'), ('andijon', 'Andijon'), ('namangan', 'Namangan'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', 'Qoraqalpog‘iston')], max_length=100, verbose_name='Viloyat')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('narx', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Narx')),
                ('asosiyimg', models.ImageField(upload_to='asosiyimg/', verbose_name='Asosiy rasm')),
                ('birimg', models.ImageField(blank=True, null=True, upload_to='birimg/', verbose_name='1-rasm')),
                ('ikkiimg', models.ImageField(blank=True, null=True, upload_to='ikkiimg/', verbose_name='2-rasm')),
                ('uchuimg', models.ImageField(blank=True, null=True, upload_to='uchuimg/', verbose_name='3-rasm')),
                ('toltirish', models.FileField(blank=True, null=True, upload_to='toltirish/', verbose_name="Qo'shimcha fayl")),
                ('sotilgan', models.BooleanField(default=False, verbose_name='Sotildi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
