# Generated by Django 5.2.4 on 2025-10-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='user',
        ),
    ]
