# Generated by Django 5.2.4 on 2025-10-27 15:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0005_alter_mahsulot_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Narx'),
        ),
    ]
