# Generated by Django 5.2.4 on 2025-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0006_alter_mahsulot_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.CharField(default='0', max_length=20, verbose_name='Narx'),
        ),
    ]
