# Generated by Django 5.2.4 on 2025-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0007_alter_mahsulot_narx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['-sana'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='korishlar_soni',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Aniq manzil'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='tavsif',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil tavsif'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='tuman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar'),
        ),
    ]
