# Generated by Django 5.2.4 on 2026-01-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner nomi')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner rasmi')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop/Notebook'), ('mobile', 'Mobile/Tablet')], max_length=10, verbose_name='Qurilma turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
