# Generated by Django 5.2.4 on 2026-01-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_nomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=20, verbose_name='Admin raqami')),
            ],
        ),
    ]
