# Generated by Django 5.2.4 on 2026-01-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0011_admin_nomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_nomer',
            new_name='AdminNomer',
        ),
    ]
