# Generated by Django 5.2.4 on 2026-01-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0012_rename_admin_nomer_adminnomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnomer',
            name='telfon',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
