# Generated by Django 5.2.4 on 2026-01-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0013_adminnomer_telfon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnomer',
            old_name='telfon',
            new_name='telefon',
        ),
        migrations.AddField(
            model_name='adminnomer',
            name='support_link',
            field=models.URLField(blank=True, null=True, verbose_name='Support havolasi'),
        ),
        migrations.AddField(
            model_name='adminnomer',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram havolasi'),
        ),
        migrations.AlterField(
            model_name='adminnomer',
            name='nomer',
            field=models.CharField(max_length=20, verbose_name='Admin nomi'),
        ),
    ]
