# Generated by Django 5.2.4 on 2026-01-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0014_rename_telfon_adminnomer_telefon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AloqaMalumotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Manzil nomi')),
                ('manzil_turi', models.CharField(choices=[('bosh_ofis', 'Bosh ofis'), ('filial', 'Filial'), ('support', "Qo'llab-quvvatlash markazi")], default='bosh_ofis', max_length=20, verbose_name='Manzil turi')),
                ('viloyat', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('tuman', models.CharField(max_length=100, verbose_name='Tuman/Shahar')),
                ('aniq_manzil', models.TextField(verbose_name='Aniq manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email manzili')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook havolasi')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram havolasi')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram havolasi')),
                ('telegram_bot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram bot username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': "Aloqa ma'lumoti",
                'verbose_name_plural': "Aloqa ma'lumotlari",
                'ordering': ['tartib', 'viloyat'],
            },
        ),
        migrations.CreateModel(
            name='FooterSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('qisqacha_tavsif', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('copyright_matn', models.TextField(default='© 2025 Tez Sot. Barcha huquqlar himoyalangan.', verbose_name='Copyright matni')),
                ('maxfiylik_siyosati', models.URLField(verbose_name='Maxfiylik siyosati havolasi')),
                ('foydalanish_shartlari', models.URLField(verbose_name='Foydalanish shartlari havolasi')),
                ('qoidalar', models.URLField(verbose_name='Qoidalar havolasi')),
                ('faq', models.URLField(blank=True, null=True, verbose_name='FAQ havolasi')),
            ],
            options={
                'verbose_name': 'Footer sozlamalari',
                'verbose_name_plural': 'Footer sozlamalari',
            },
        ),
        migrations.AlterModelOptions(
            name='adminnomer',
            options={'verbose_name': 'Admin nomer', 'verbose_name_plural': 'Admin nomerlar'},
        ),
    ]
