# Generated by Django 5.2.4 on 2026-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0015_aloqamalumotlari_footersozlamalari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AloqaSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(default='Tez Sot Market', max_length=200, verbose_name='Kompaniya nomi')),
                ('qisqacha_tavsif', models.TextField(default='Eng tez va ishonchli onlayn savdo platformasi', verbose_name='Qisqacha tavsif')),
                ('manzil_viloyat', models.CharField(default='Andijon', max_length=100, verbose_name='Viloyat')),
                ('manzil_tuman', models.CharField(default='Izboskan tumani', max_length=100, verbose_name='Tuman')),
                ('aniq_manzil', models.TextField(blank=True, null=True, verbose_name='Aniq manzil')),
                ('telefon_1', models.CharField(default='+998 33 301 33 31', max_length=20, verbose_name='Asosiy telefon')),
                ('telefon_2', models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(default='humoyun731uzb@gmail.com', max_length=254, verbose_name='Email manzili')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('telegram_bot', models.CharField(default='@tezsot_support_bot', max_length=100, verbose_name='Telegram bot username')),
                ('admin_nomi', models.CharField(default='Asosiy admin', max_length=100, verbose_name='Admin nomi')),
                ('admin_telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Admin telefon')),
                ('admin_telegram', models.URLField(blank=True, null=True, verbose_name='Admin Telegram')),
                ('support_link', models.URLField(blank=True, null=True, verbose_name='Support havolasi')),
                ('biz_haqimizda', models.CharField(default='/bizhaqimizda/', max_length=200, verbose_name='Biz haqimizda havolasi')),
                ('maxfiylik_siyosati', models.CharField(default='/maxfiyliksiyosati/', max_length=200, verbose_name='Maxfiylik siyosati')),
                ('qoidalar', models.CharField(default='/qoidalar/', max_length=200, verbose_name='Qoidalar')),
                ('boglanish', models.CharField(default='/boglanish/', max_length=200, verbose_name="Bog'lanish")),
                ('copyright_matn', models.TextField(default='© 2025 Tez Sot. Barcha huquqlar himoyalangan.', verbose_name='Copyright matni')),
                ('yangilangan', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Aloqa sozlamalari',
                'verbose_name_plural': 'Aloqa sozlamalari',
            },
        ),
        migrations.DeleteModel(
            name='AdminNomer',
        ),
        migrations.DeleteModel(
            name='AloqaMalumotlari',
        ),
        migrations.DeleteModel(
            name='FooterSozlamalari',
        ),
    ]
