# Generated by Django 5.2.4 on 2026-01-04 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0016_aloqasozlamalari_delete_adminnomer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name="Bio (Qisqacha ma'lumot)")),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram username')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('work_hours_start', models.TimeField(default='09:00', verbose_name='Ish vaqti boshlanishi')),
                ('work_hours_end', models.TimeField(default='21:00', verbose_name='Ish vaqti tugashi')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='seller_profile_images/', verbose_name='Profil rasmi')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='seller_banners/', verbose_name='Banner rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sotuvchi Profili',
                'verbose_name_plural': 'Sotuvchi Profillari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AloqaSozlamalari',
        ),
    ]
