# Generated by Django 5.2.4 on 2026-01-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0017_sellerprofile_delete_aloqasozlamalari'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=255, verbose_name='Manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('telegram', models.URLField(verbose_name='Telegram havolasi')),
                ('instagram', models.URLField(verbose_name='Instagram havolasi')),
                ('facebook', models.URLField(verbose_name='Facebook havolasi')),
            ],
            options={
                'verbose_name': 'Admin Aloqa',
            },
        ),
    ]
