# Generated by Django 5.2.4 on 2026-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0018_adminaloqa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaloqa',
            options={},
        ),
        migrations.AlterField(
            model_name='adminaloqa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='adminaloqa',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook havolasi'),
        ),
        migrations.AlterField(
            model_name='adminaloqa',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram havolasi'),
        ),
        migrations.AlterField(
            model_name='adminaloqa',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram havolasi'),
        ),
    ]
