# Generated by Django 5.2.4 on 2026-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0019_alter_adminaloqa_options_alter_adminaloqa_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('kitob', 'Kitob'), ('mebel', 'Mebel'), ('cheteltovarlar', 'Cheteltovarlar'), ('uyjoyelonlari', 'Uyjoyelonlari'), ('onavabollar', 'Onavabollar'), ('avto_elonlari', 'Avto elonlari'), ('uy_jihozlari', 'Uy jihozlari'), ('kiyim', 'Kiyim-kechak'), ('avto', 'Avto ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya'),
        ),
    ]
