# Generated by Django 5.2.4 on 2026-01-06 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0020_alter_mahsulot_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket nomi')),
                ('package_type', models.CharField(choices=[('free', 'Bepul (Standart)'), ('basic', 'Asosiy'), ('pro', 'Professional'), ('business', 'Biznes'), ('unlimited', 'Cheksiz')], max_length=20, verbose_name='Paket turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('max_vip', models.IntegerField(default=0, verbose_name='Maksimal VIP')),
                ('max_premium', models.IntegerField(default=0, verbose_name='Maksimal Premium')),
                ('max_featured', models.IntegerField(default=0, verbose_name='Maksimal Featured')),
                ('max_urgent', models.IntegerField(default=0, verbose_name='Maksimal Urgent')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Muddati (kun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ommabop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top Mahsulot Paketi',
                'verbose_name_plural': 'Top Mahsulot Paketlari',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Top mahsulot'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='top_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Top muddati tugashi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='top_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Top turi'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='max_top_products',
            field=models.IntegerField(default=1, verbose_name='Maksimal top mahsulotlar'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='used_top_products',
            field=models.IntegerField(default=0, verbose_name='Foydalanilgan top mahsulotlar'),
        ),
        migrations.CreateModel(
            name='TopProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_type', models.CharField(choices=[('vip', 'VIP Mahsulot'), ('premium', 'Premium Mahsulot'), ('featured', "Ko'rib chiqilgan"), ('urgent', 'Shoshilinch')], max_length=20, verbose_name='Top turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('completed', 'Yakunlangan')], default='pending', max_length=20, verbose_name='Holati')),
                ('requested_days', models.IntegerField(default=7, verbose_name="So'ralgan kunlar")),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan sana')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fronend.mahsulot', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Top Mahsulot So'rovi",
                'verbose_name_plural': "Top Mahsulot So'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTopProductSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('expired', 'Muddati otgan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holati')),
                ('used_vip', models.IntegerField(default=0, verbose_name='Foydalanilgan VIP')),
                ('used_premium', models.IntegerField(default=0, verbose_name='Foydalanilgan Premium')),
                ('used_featured', models.IntegerField(default=0, verbose_name='Foydalanilgan Featured')),
                ('used_urgent', models.IntegerField(default=0, verbose_name='Foydalanilgan Urgent')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="To'lov summasi")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fronend.topproductpackage', verbose_name='Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Top Mahsulot Obunasi',
                'verbose_name_plural': 'Top Mahsulot Obunalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Yakunlangan'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name="To'lov usuli")),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Tranzaksiya ID')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan sana")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('top_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fronend.topproductrequest', verbose_name="Top so'rovi")),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fronend.usertopproductsubscription', verbose_name='Obuna')),
            ],
            options={
                'verbose_name': "Top Mahsulot To'lovi",
                'verbose_name_plural': "Top Mahsulot To'lovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
