# Generated by Django 5.2.4 on 2026-01-07 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0021_topproductpackage_category_icon_mahsulot_is_top_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPremiumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_premium_products', models.PositiveIntegerField(default=10, verbose_name='Max premium mahsulotlar')),
                ('premium_duration_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Premium muddati (kun)')),
                ('is_premium_enabled', models.BooleanField(default=True, verbose_name='Premium tizim yoqilganmi')),
                ('admin_contact_phone', models.CharField(default='+998901234567', max_length=20, verbose_name='Admin telefon raqami')),
                ('admin_contact_telegram', models.CharField(default='@admin_username', max_length=100, verbose_name='Admin Telegram')),
                ('admin_contact_email', models.EmailField(default='admin@tezsot.uz', max_length=254, verbose_name='Admin Email')),
                ('premium_fee_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name="Premium to'lov miqdori")),
                ('require_admin_approval', models.BooleanField(default=True, verbose_name='Admin tasdigi talab qilinadimi')),
                ('auto_approve_premium', models.BooleanField(default=False, verbose_name='Premium mahsulotlarni avtomatik tasdiqlash')),
                ('premium_badge_color', models.CharField(default='#FFD700', max_length=20, verbose_name='Premium badge rangi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Sozlamalar',
                'verbose_name_plural': 'Premium Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Premium mahsulotmi')),
                ('admin_approved', models.BooleanField(default=False, verbose_name='Admin tasdiqlaganmi')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('premium_since', models.DateTimeField(auto_now_add=True, verbose_name='Premium boshlangan sana')),
                ('featured_until', models.DateTimeField(blank=True, null=True, verbose_name='Featured tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Premium aktivmi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha eslatmalar")),
            ],
            options={
                'verbose_name': 'Premium Mahsulot',
                'verbose_name_plural': 'Premium Mahsulotlar',
                'ordering': ['-premium_since'],
            },
        ),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('user_premium', 'Premium foydalanuvchi'), ('product_premium', 'Premium mahsulot'), ('seller_premium', 'Premium sotuvchi')], max_length=50, verbose_name="So'rov turi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('requested_days', models.PositiveIntegerField(default=30, verbose_name="So'ralgan kunlar")),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='premium_payments/', verbose_name="To'lov dalili")),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin eslatmalari')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Admin javobi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Premium So'rovi",
                'verbose_name_plural': "Premium So'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium status')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan')], default='pending', max_length=20, verbose_name='Holati')),
                ('premium_since', models.DateTimeField(blank=True, null=True, verbose_name='Premium boshlangan sana')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash sanasi')),
                ('admin_approved', models.BooleanField(default=False, verbose_name='Admin tasdiqlaganmi')),
                ('premium_limit', models.PositiveIntegerField(default=5, verbose_name='Premium mahsulot limiti')),
                ('premium_used', models.PositiveIntegerField(default=0, verbose_name='Foydalanilgan premium mahsulotlar')),
                ('premium_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Premium to'lov miqdori")),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli")),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha eslatmalar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Foydalanuvchi',
                'verbose_name_plural': 'Premium Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='usertopproductsubscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='topproductpayment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='topproductpayment',
            name='top_request',
        ),
        migrations.RemoveField(
            model_name='topproductpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topproductrequest',
            name='mahsulot',
        ),
        migrations.RemoveField(
            model_name='topproductrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertopproductsubscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['-premium_priority', '-premium_since', '-sana'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='top_ends_at',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='top_type',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='max_top_products',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='used_top_products',
        ),
        migrations.AddField(
            model_name='category',
            name='has_premium',
            field=models.BooleanField(default=False, verbose_name='Premium kategoriyami'),
        ),
        migrations.AddField(
            model_name='category',
            name='premium_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Premium to'lov"),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Featured tugash sanasi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured mahsulotmi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium mahsulotmi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Premium prioritet'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium boshlangan sana'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_premium_seller',
            field=models.BooleanField(default=False, verbose_name='Premium sotuvchimi'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='premium_seller_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium sotuvchi boshlanishi'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Sotuvchi reytingi'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami sotuvlar'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['is_premium', 'aktiv', 'sotilgan'], name='fronend_mah_is_prem_4882c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['premium_since'], name='fronend_mah_premium_44952c_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['category', 'aktiv'], name='fronend_mah_categor_bee027_idx'),
        ),
        migrations.AddField(
            model_name='premiumproduct',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_premium_products', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin'),
        ),
        migrations.AddField(
            model_name='premiumproduct',
            name='mahsulot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_info', to='fronend.mahsulot', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='premiumproduct',
            name='premium_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_products', to=settings.AUTH_USER_MODEL, verbose_name='Premium egasi'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fronend.mahsulot', verbose_name="Mahsulot (agar mahsulot premium bo'lsa)"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.DeleteModel(
            name='TopProductPackage',
        ),
        migrations.DeleteModel(
            name='TopProductPayment',
        ),
        migrations.DeleteModel(
            name='TopProductRequest',
        ),
        migrations.DeleteModel(
            name='UserTopProductSubscription',
        ),
        migrations.AddIndex(
            model_name='premiumproduct',
            index=models.Index(fields=['admin_approved', 'is_active'], name='fronend_pre_admin_a_0050a6_idx'),
        ),
    ]
