# Generated by Django 5.2.4 on 2026-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0022_adminpremiumsettings_premiumproduct_premiumrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumuser',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_fee',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin izohlari'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="So'rov sanasi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='request_premium_access',
            field=models.BooleanField(default=False, verbose_name="Premium so'rovi"),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('active', 'Faol')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
