# Generated by Django 5.2.4 on 2026-01-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0023_remove_premiumuser_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['-is_premium', '-premium_priority', '-premium_since', '-sana'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
