# Generated by Django 5.2.4 on 2026-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0024_alter_mahsulot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['-premium_priority', '-premium_since', '-sana'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='category',
            field=models.CharField(choices=[('elektronika', 'Elektronika'), ('kitob', 'Kitoblar'), ('mebel', 'Mebellar'), ('cheteltovarlar', 'Chet el tovarlari'), ('uyjoyelonlari', 'Uy joy elonlari'), ('onavabollar', 'Onalar va bolalar'), ('avto_elonlari', 'Auto elonlar'), ('uy_jihozlari', 'Uy jihozlari'), ('kiyim', 'Kiyim-kechak'), ('avto', 'Avto ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya'),
        ),
    ]
