# Generated by Django 5.2.10 on 2026-01-14 04:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0025_alter_mahsulot_options_alter_mahsulot_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='premiumrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='premiumrequest',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='mahsulot',
            name='fronend_mah_premium_44952c_idx',
        ),
        migrations.RemoveField(
            model_name='premiumproduct',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='premiumproduct',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_since',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_until',
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='can_reactivate_old',
            field=models.BooleanField(default=False, help_text="Agar yoqilsa, qayta premium olinganda eski e'lonlar ham premium bo'ladi", verbose_name="Eski e'lonlarni qayta premium qilish mumkinmi"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='check_expiry_every_hours',
            field=models.PositiveIntegerField(default=1, help_text='Necha soatda bir premium muddati tekshiriladi', verbose_name='Premium vaqtini tekshirish (soat)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=3, help_text='Premium tugashidan necha kun oldin ogohlantirish yuboriladi', verbose_name='Premium tugashidan oldin ogohlantirish (kun)'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_admin_approved',
            field=models.BooleanField(default=False, verbose_name='Premium admin tasdiqladi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Premium kunlari'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash sanasi'),
        ),
        migrations.AddField(
            model_name='premiumproduct',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash sanasi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tekshirilgan vaqt'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='notified_before_expiry',
            field=models.BooleanField(default=False, verbose_name='Premium tugashidan ogohlantirildi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Premium kunlari'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium tugash vaqti'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_products',
            field=models.PositiveIntegerField(default=5, help_text="Bir premium foydalanuvchi uchun max premium e'lonlar soni", verbose_name='Max premium mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_duration_days',
            field=models.PositiveIntegerField(default=30, help_text="Premium foydalanuvchi necha kun premium bo'lishi", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Premium muddati (kun)'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['premium_since', 'premium_expiry'], name='fronend_mah_premium_8e0d05_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumproduct',
            index=models.Index(fields=['premium_until'], name='fronend_pre_premium_e1c474_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['premium_end', 'is_premium', 'status'], name='fronend_pre_premium_5c6cc4_idx'),
        ),
        migrations.DeleteModel(
            name='PremiumRequest',
        ),
    ]
