# Generated by Django 4.2 on 2026-01-15 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0026_remove_premiumrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_check_expiry',
            field=models.BooleanField(default=True, verbose_name='Premium muddatini avtomatik tekshirish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
            field=models.PositiveIntegerField(default=3, verbose_name="Bir foydalanuvchi uchun max so'rovlar soni"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
            field=models.PositiveIntegerField(default=7, help_text="Premium so'rovi necha kundan keyin o'chiriladi", verbose_name="Premium so'rov muddati (kun)"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='send_notifications',
            field=models.BooleanField(default=True, verbose_name='Ogohlantirishlarni yuborish'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='premium_views',
            field=models.PositiveIntegerField(default=0, verbose_name="Premium ko'rishlar"),
        ),
        migrations.CreateModel(
            name='PremiumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('requested_days', models.PositiveIntegerField(default=30, verbose_name="So'ralgan kunlar")),
                ('requested_limit', models.PositiveIntegerField(default=5, verbose_name="So'ralgan limit")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha eslatmalar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan')], default='pending', max_length=20, verbose_name='Holati')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin izohlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Premium So'rovi",
                'verbose_name_plural': "Premium So'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expiry_soon', 'Premium muddati tugash arafasida'), ('expired', 'Premium muddati tugadi'), ('new_request', "Yangi premium so'rovi"), ('admin_action', 'Admin harakati'), ('product_limit', 'Mahsulot limiti tugab qoldi')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['status', 'created_at'], name='fronend_pre_status_42b63c_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['user', 'status'], name='fronend_pre_user_id_8f64d7_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumnotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='fronend_pre_user_id_93fcf5_idx'),
        ),
    ]
