# Generated by Django 4.2 on 2026-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0027_adminpremiumsettings_auto_check_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, help_text='Premium muddati tugaganda necha kun uzaytiriladi', verbose_name='Avtomatik uzaytirish kunlari'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_renew_premium',
            field=models.BooleanField(default=False, help_text='Agar yoqilsa, premium muddati tugaganda avtomatik uzaytiriladi', verbose_name='Premiumni avtomatik uzaytirish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='notify_on_auto_renew',
            field=models.BooleanField(default=True, verbose_name='Avtomatik uzaytirish haqida xabar berish'),
        ),
        migrations.AlterField(
            model_name='premiumnotification',
            name='notification_type',
            field=models.CharField(choices=[('expiry_soon', 'Premium muddati tugash arafasida'), ('expired', 'Premium muddati tugadi'), ('new_request', "Yangi premium so'rovi"), ('admin_action', 'Admin harakati'), ('product_limit', 'Mahsulot limiti tugab qoldi'), ('auto_renewed', 'Premium avtomatik uzaytirildi')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['user'], name='fronend_mah_user_id_5c158f_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['phone'], name='fronend_pre_phone_dce3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['user'], name='fronend_pre_user_id_f071db_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['phone'], name='fronend_sel_phone_5ff2e6_idx'),
        ),
    ]
