# Generated by Django 4.2 on 2026-01-23 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0028_adminpremiumsettings_auto_renew_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_card_number',
            field=models.CharField(blank=True, help_text="To'lov qilish uchun bank karta raqami", max_length=50, null=True, verbose_name='Bank karta raqami'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank nomi', max_length=100, null=True, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='discount_end_date',
            field=models.DateField(blank=True, help_text='Chegirma tugash sanasi (ixtiyoriy)', null=True, verbose_name='Chegirma tugash sanasi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, help_text="Premium to'lov uchun chegirma foizi (0-50%)", validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Chegirma foizi (%)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='discount_start_date',
            field=models.DateField(blank=True, help_text='Chegirma boshlanish sanasi (ixtiyoriy)', null=True, verbose_name='Chegirma boshlanish sanasi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='enable_premium_stats',
            field=models.BooleanField(default=True, help_text="Premium statistikasini to'plash va ko'rsatish", verbose_name='Premium statistikasini yoqish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='has_discount',
            field=models.BooleanField(default=False, help_text='Agar yoqilsa, chegirma narxlari faollashtiriladi', verbose_name='Chegirma mavjudmi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text="To'lov qilish bo'yicha ko'rsatmalar", null=True, verbose_name="To'lov ko'rsatmalari"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_methods',
            field=models.JSONField(default=list, help_text="Qabul qilinadigan to'lov usullari (JSON formatda)", verbose_name="To'lov usullari"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_badge_text',
            field=models.CharField(default='PREMIUM', max_length=50, verbose_name='Premium badge matni'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_3months_price',
            field=models.DecimalField(decimal_places=2, default=150000.0, help_text="3 oylik premium uchun to'lov miqdori (90 kun)", max_digits=10, verbose_name='3 oylik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_6months_price',
            field=models.DecimalField(decimal_places=2, default=270000.0, help_text="6 oylik premium uchun to'lov miqdori (180 kun)", max_digits=10, verbose_name='6 oylik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_day_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text="1 kunlik premium uchun to'lov miqdori", max_digits=10, verbose_name='Kunlik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_month_price',
            field=models.DecimalField(decimal_places=2, default=60000.0, help_text="1 oylik premium uchun to'lov miqdori (30 kun)", max_digits=10, verbose_name='Oylik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_week_price',
            field=models.DecimalField(decimal_places=2, default=12000.0, help_text="1 haftalik premium uchun to'lov miqdori (7 kun)", max_digits=10, verbose_name='Haftalik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_per_year_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, help_text="1 yillik premium uchun to'lov miqdori (365 kun)", max_digits=10, verbose_name='Yillik premium narx'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Premium mahsulotlarning muvaffaqiyat darajasi', max_digits=5, verbose_name='Premium muvaffaqiyat darajasi (%)'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='calculated_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hisoblangan summa'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_telegram',
            field=models.CharField(default='@tezsot_admin', max_length=100, verbose_name='Admin Telegram'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_approve_premium',
            field=models.BooleanField(default=False, help_text='Premium mahsulotlar avtomatik tasdiqlansinmi', verbose_name='Premium mahsulotlarni avtomatik tasdiqlash'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_check_expiry',
            field=models.BooleanField(default=True, help_text="Premium muddati o'tgan foydalanuvchilarni avtomatik tekshirish", verbose_name='Premium muddatini avtomatik tekshirish'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, help_text='Premium muddati tugaganda necha kun uzaytiriladi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Avtomatik uzaytirish kunlari'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='check_expiry_every_hours',
            field=models.PositiveIntegerField(default=1, help_text='Necha soatda bir premium muddati tekshiriladi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Premium vaqtini tekshirish (soat)'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
            field=models.PositiveIntegerField(default=3, help_text="Bir foydalanuvchi oyiga nechta premium so'rov yuborishi mumkin", verbose_name="Bir foydalanuvchi uchun max so'rovlar soni"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=3, help_text='Premium tugashidan necha kun oldin ogohlantirish yuboriladi', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Premium tugashidan oldin ogohlantirish (kun)'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='notify_on_auto_renew',
            field=models.BooleanField(default=True, help_text="Avtomatik uzaytirish bo'lsa foydalanuvchiga xabar berish", verbose_name='Avtomatik uzaytirish haqida xabar berish'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text="1 ta mahsulotni premium qilish uchun to'lov miqdori", max_digits=10, verbose_name='1 ta mahsulot uchun premium narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
            field=models.PositiveIntegerField(default=7, help_text="Premium so'rovi necha kundan keyin o'chiriladi", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name="Premium so'rov muddati (kun)"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, help_text="Premium so'rovlar admin tasdigini talab qiladimi", verbose_name='Admin tasdigi talab qilinadimi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Foydalanuvchilarga ogohlantirish xabarlarini yuborish', verbose_name='Ogohlantirishlarni yuborish'),
        ),
    ]
