# Generated by Django 4.2 on 2026-01-23 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0029_adminpremiumsettings_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='affiliate_percentage',
            field=models.PositiveIntegerField(default=10, help_text='Hamkorlik dasturi uchun foiz', validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Hamkorlik foizi (%)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_card_owner',
            field=models.CharField(blank=True, help_text='Bank karta egasining ismi', max_length=100, null=True, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='enable_affiliate_program',
            field=models.BooleanField(default=False, help_text='Premium foydalanuvchilarga hamkorlik dasturi', verbose_name='Hamkorlik dasturini yoqish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, help_text='Foydalanuvchilarga SMS orqali bildirishnoma yuborish', verbose_name='SMS bildirishnomalarni yoqish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='enable_test_period',
            field=models.BooleanField(default=False, help_text='Premium uchun sinov muddati berish', verbose_name='Sinov muddatini yoqish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text='SMS yuborish uchun API kaliti', max_length=255, null=True, verbose_name='SMS API kaliti'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='sms_sender_name',
            field=models.CharField(blank=True, default='TezSot', help_text='SMS yuboruvchi nomi', max_length=50, null=True, verbose_name='SMS yuboruvchi nomi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='test_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Sinov muddati kunlari', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Sinov muddati (kun)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='total_premium_products',
            field=models.PositiveIntegerField(default=0, help_text='Premium mahsulotlar soni', verbose_name='Jami premium mahsulotlar'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='total_premium_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Premium to'lovlardan jami daromad", max_digits=15, verbose_name='Jami premium daromad'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='total_premium_users',
            field=models.PositiveIntegerField(default=0, help_text='Premium foydalanuvchilar soni', verbose_name='Jami premium foydalanuvchilar'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_card_number',
            field=models.CharField(blank=True, help_text="To'lov qilish uchun bank karta raqami (masalan: 8600 1234 5678 9012)", max_length=50, null=True, verbose_name='Bank karta raqami'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank nomi (masalan: Xalq banki, Kapital bank)', max_length=100, null=True, verbose_name='Bank nomi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='payment_methods',
            field=models.TextField(blank=True, help_text="Qabul qilinadigan to'lov usullari (har biri yangi qatorda yozing)", null=True, verbose_name="To'lov usullari"),
        ),
    ]
