# Generated by Django 4.2 on 2026-01-23 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0030_adminpremiumsettings_affiliate_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='affiliate_percentage',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='auto_approve_premium',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='auto_check_expiry',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='auto_renew_premium',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='can_reactivate_old',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='check_expiry_every_hours',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='discount_start_date',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='enable_affiliate_program',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='enable_premium_stats',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='enable_sms_notifications',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='enable_test_period',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='notify_on_auto_renew',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='payment_instructions',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='premium_badge_color',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='premium_badge_text',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='premium_duration_days',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='premium_success_rate',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='send_notifications',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='sms_api_key',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='sms_sender_name',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='test_period_days',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='total_premium_products',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='total_premium_revenue',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='total_premium_users',
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_card_number',
            field=models.CharField(blank=True, help_text="To'lov qilish uchun karta raqami", max_length=50, null=True, verbose_name='Bank karta raqami'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_card_owner',
            field=models.CharField(blank=True, help_text='Karta egasining ismi', max_length=100, null=True, verbose_name='Karta egasi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank nomi', max_length=100, null=True, verbose_name='Bank nomi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, help_text='Chegirma foizi (%)', validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='has_discount',
            field=models.BooleanField(default=False, help_text='Premium uchun chegirma mavjudmi?', verbose_name='Chegirma yoqilsinmi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_products',
            field=models.PositiveIntegerField(default=5, help_text='1 premium foydalanuvchi uchun max mahsulotlar', verbose_name='Premium mahsulot limiti'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='payment_methods',
            field=models.TextField(blank=True, default='Bank karta\nClick\nPayme\nUzumbank', help_text='Har bir usul yangi qatorda', null=True, verbose_name="To'lov usullari"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='1 ta mahsulotni premium qilish uchun narx', max_digits=10, verbose_name='1 ta mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_3months_price',
            field=models.DecimalField(decimal_places=2, default=150000.0, help_text='3 oylik premium narx (90 kun)', max_digits=10, verbose_name='3 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_6months_price',
            field=models.DecimalField(decimal_places=2, default=270000.0, help_text='6 oylik premium narx (180 kun)', max_digits=10, verbose_name='6 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_day_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='1 kunlik premium uchun narx', max_digits=10, verbose_name='Kunlik premium narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_month_price',
            field=models.DecimalField(decimal_places=2, default=60000.0, help_text='1 oylik premium narx (30 kun)', max_digits=10, verbose_name='1 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_week_price',
            field=models.DecimalField(decimal_places=2, default=12000.0, help_text='1 haftalik premium narx (7 kun)', max_digits=10, verbose_name='1 haftalik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_year_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, help_text='1 yillik premium narx (365 kun)', max_digits=10, verbose_name='1 yillik narx'),
        ),
    ]
