# Generated by Django 4.2 on 2026-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0031_remove_adminpremiumsettings_affiliate_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
            field=models.PositiveIntegerField(default=3, help_text="1 foydalanuvchi oyiga nechta so'rov yuborishi mumkin", verbose_name="Premium so'rovlar limiti"),
        ),
    ]
