# Generated by Django 4.2 on 2026-01-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0032_adminpremiumsettings_max_premium_requests_per_user'),
    ]

    operations = [
    ]
