# Generated by Django 4.2 on 2026-01-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0033_merge_20260123_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Toʻlangan'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['payment_status'], name='fronend_pre_payment_263ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['transaction_id'], name='fronend_pre_transac_7555fc_idx'),
        ),
    ]
