# Generated by Django 4.2 on 2026-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0035_premiumrequest_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_approve_premium',
            field=models.BooleanField(default=False, help_text='Premium mahsulotlarni avtomatik tasdiqlash', verbose_name='Premiumni avtomatik tasdiqlash'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, help_text='Avtomatik uzaytiriladigan kunlar soni', verbose_name='Avtomatik uzaytirish kuni'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_renew_premium',
            field=models.BooleanField(default=False, help_text='Premium muddati tugaganda avtomatik uzaytirish', verbose_name='Premiumni avtomatik uzaytirish'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=3, help_text='Premium tugashidan necha kun oldin ogohlantirish', verbose_name='Ogohlantirish kuni'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Premium obuna muddati kunlarda', verbose_name='Premium muddati (kun)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
            field=models.PositiveIntegerField(default=7, help_text="Premium so'rov qancha kunga amal qiladi", verbose_name="Premium so'rov muddati"),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, help_text="Premium so'rovlar admin tasdigini talab qilsinmi?", verbose_name='Admin tasdigini talab qilish'),
        ),
    ]
