# Generated by Django 4.2 on 2026-01-26 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0036_adminpremiumsettings_auto_approve_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='active_premium_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Faol premium mahsulotlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_premium_users', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='auto_renew_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Avtomatik uzaytirishlar soni'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Avtomatik uzaytirish kuni'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='bonus_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus kunlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='bonus_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus limit'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='can_extend',
            field=models.BooleanField(default=True, verbose_name='Uzatish mumkinmi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='can_pause',
            field=models.BooleanField(default=False, verbose_name="To'xtatish mumkinmi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='can_transfer',
            field=models.BooleanField(default=False, verbose_name="O'tkazish mumkinmi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='daily_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Kunlik mahsulot limiti'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='daily_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Kunlik foydalanilgan'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Chegirma summasi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='discount_applied',
            field=models.BooleanField(default=False, verbose_name="Chegirma qo'llanilganmi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma foizi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='first_premium_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birinchi premium sanasi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='is_auto_renew',
            field=models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='last_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Oxirgi to'lov summasi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='last_premium_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi premium sanasi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='next_auto_renew',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Keyingi avtomatik uzaytirish'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='notified_after_expiry',
            field=models.BooleanField(default=False, verbose_name='Premium tugaganidan ogohlantirildi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='notified_limit_warning',
            field=models.BooleanField(default=False, verbose_name='Limit ogohlantirish'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan vaqtgacha"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov havolasi"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Toʻlanmagan'), ('paid', 'Toʻlangan'), ('partial', 'Qisman toʻlangan'), ('overdue', 'Muddati otgan'), ('refunded', 'Qaytarilgan')], default='unpaid', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Premium bosishlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Premium reytingi'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='premium_views',
            field=models.PositiveIntegerField(default=0, verbose_name="Premium ko'rishlar"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Baholar soni'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='request_notes',
            field=models.TextField(blank=True, null=True, verbose_name="So'rov izohlari"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='sold_premium_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Sotilgan premium mahsulotlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Jami to'lovlar"),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='total_premium_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami premium mahsulotlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='total_purchased_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami sotib olingan kunlar'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='total_purchased_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami sotib olingan limit'),
        ),
        migrations.AddField(
            model_name='premiumuser',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Foydalanuvchi izohlari'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='premium_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Premium kunlari'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('active', 'Faol'), ('suspended', "To'xtatilgan"), ('cancelled', 'Bekor qilingan'), ('waiting_payment', "To'lov kutilyapti")], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['status', 'premium_end'], name='fronend_pre_status_5b16e9_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['payment_status'], name='fronend_pre_payment_e169a8_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['is_auto_renew'], name='fronend_pre_is_auto_1ef4de_idx'),
        ),
    ]
