# Generated by Django 4.2 on 2026-01-26 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0037_premiumuser_active_premium_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumrequest',
            options={'ordering': ['-priority', '-created_at'], 'permissions': [('can_approve_requests', "Premium so'rovlarni tasdiqlash huquqi"), ('can_reject_requests', "Premium so'rovlarni rad etish huquqi"), ('can_view_payment_proof', "To'lov dalillarini ko'rish huquqi"), ('can_export_requests', "So'rovlarni export qilish huquqi")], 'verbose_name': "Premium So'rovi", 'verbose_name_plural': "Premium So'rovlari"},
        ),
        migrations.RemoveIndex(
            model_name='premiumuser',
            name='fronend_pre_status_5b16e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='premiumuser',
            name='fronend_pre_payment_e169a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='premiumuser',
            name='fronend_pre_is_auto_1ef4de_idx',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='active_premium_products',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='auto_renew_count',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='auto_renew_days',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='bonus_days',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='bonus_limit',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='can_extend',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='can_pause',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='can_transfer',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='daily_used',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='first_premium_date',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='is_auto_renew',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='last_payment_amount',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='last_premium_date',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='next_auto_renew',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='notified_after_expiry',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='notified_limit_warning',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='paused_until',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_clicks',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_rating',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='premium_views',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='request_notes',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='sold_premium_products',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='total_payments',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='total_premium_products',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='total_purchased_days',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='total_purchased_limit',
        ),
        migrations.RemoveField(
            model_name='premiumuser',
            name='user_notes',
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Qayta ishlagan admin'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='auto_approve',
            field=models.BooleanField(default=False, help_text="To'lov tasdiqlangandan so'ng avtomatik tasdiqlansinmi?", verbose_name='Avtomatik tasdiqlansinmi'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muddati tugagan sana'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Bildirishnoma yuborilganmi'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='payment_proof',
            field=models.FileField(blank=True, help_text="To'lov cheki yoki skrinshoti", null=True, upload_to='payment_proofs/', verbose_name="To'lov dalili"),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text="Yuqoriroq prioritet birinchi ko'rsatiladi", verbose_name='Prioritet'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Agar so'rov rad etilsa, sababi", null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='premiumrequest',
            name='viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name="Admin ko'rganmi"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Admin qo'shimcha izohlari", null=True, verbose_name='Admin izohlari'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='calculated_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tizim tomonidan hisoblangan summa', max_digits=12, verbose_name='Hisoblangan summa'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Iltimos, haqiqiy email kiriting', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='full_name',
            field=models.CharField(help_text='Ism va familiyangizni kiriting', max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='notes',
            field=models.TextField(blank=True, help_text="Foydalanuvchi qo'shimcha ma'lumotlari", null=True, verbose_name="Qo'shimcha eslatmalar"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Foydalanuvchi to'lagan summa", max_digits=12, verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_card', 'Bank karta'), ('click', 'Click'), ('payme', 'Payme'), ('uzumbank', 'Uzumbank'), ('cash', 'Naqd pul'), ('other', 'Boshqa')], max_length=50, null=True, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Toʻlangan'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='phone',
            field=models.CharField(help_text='998XXXXXXXXX formatida kiriting', max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='requested_days',
            field=models.PositiveIntegerField(default=30, help_text='Premium obuna davomiyligi (kunlarda)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name="So'ralgan kunlar"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='requested_limit',
            field=models.PositiveIntegerField(default=5, help_text='Premium mahsulotlar soni', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name="So'ralgan limit"),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='@ belgisiz kiriting', max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank tranzaksiya raqami yoki chek nomeri', max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='premium_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Premium kunlari'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('expired', 'Muddati tugagan'), ('active', 'Faol')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['created_at'], name='fronend_pre_created_80896f_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['payment_date'], name='fronend_pre_payment_c8b5be_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumrequest',
            index=models.Index(fields=['approved_at'], name='fronend_pre_approve_2f63b7_idx'),
        ),
    ]
