# Generated by Django 5.2.11 on 2026-02-11 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0038_alter_premiumrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='bank_card_number',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='bank_card_owner',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_cards_json',
            field=models.JSONField(default=list, help_text='Bank kartalari JSON formatida', verbose_name='Bank kartalari (JSON)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_methods_json',
            field=models.JSONField(default=list, help_text="To'lov usullari JSON formatida", verbose_name="To'lov usullari (JSON)"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_email',
            field=models.EmailField(default='admin@tezsot.uz', max_length=254),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_phone',
            field=models.CharField(default='+998901234567', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_telegram',
            field=models.CharField(default='@tezsot_admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_approve_premium',
            field=models.BooleanField(default=False, verbose_name='Avtomatik tasdiqlash'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Avtomatik uzaytirish kuni'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_renew_premium',
            field=models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chegirma tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Chegirma yoqilsinmi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_products',
            field=models.PositiveIntegerField(default=5, verbose_name='Premium mahsulot limiti'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
            field=models.PositiveIntegerField(default=3, verbose_name="Premium so'rovlar limiti"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Ogohlantirish kuni'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Premium muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10, verbose_name='1 ta mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_3months_price',
            field=models.DecimalField(decimal_places=2, default=150000.0, max_digits=10, verbose_name='3 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_6months_price',
            field=models.DecimalField(decimal_places=2, default=270000.0, max_digits=10, verbose_name='6 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_day_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name='Kunlik premium narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_month_price',
            field=models.DecimalField(decimal_places=2, default=60000.0, max_digits=10, verbose_name='1 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_week_price',
            field=models.DecimalField(decimal_places=2, default=12000.0, max_digits=10, verbose_name='1 haftalik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_year_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=10, verbose_name='1 yillik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
            field=models.PositiveIntegerField(default=7, verbose_name="Premium so'rov muddati"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, verbose_name='Admin tasdigini talab qilish'),
        ),
    ]
