# Generated by Django 5.2.11 on 2026-02-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0039_remove_adminpremiumsettings_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_methods_text',
            field=models.TextField(blank=True, help_text="Har bir to'lov usulini yangi qatorga yozing. Masalan:\nHUMO\nUzCard\nVISA", null=True, verbose_name="To'lov usullari (matn)"),
        ),
    ]
