# Generated by Django 5.2.11 on 2026-02-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0040_adminpremiumsettings_payment_methods_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='payment_methods_text',
        ),
    ]
