# Generated by Django 5.2.11 on 2026-02-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0041_remove_adminpremiumsettings_payment_methods_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_email',
            field=models.EmailField(default='admin@tezsot.uz', max_length=254, verbose_name='Admin Email'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_phone',
            field=models.CharField(default='+998901234567', max_length=20, verbose_name='Admin telefon'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_telegram',
            field=models.CharField(default='@tezsot_admin', max_length=100, verbose_name='Admin Telegram'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='bank_cards_json',
            field=models.JSONField(default=list, help_text="Bank kartalari JSON formatida. Misol: [{'card_number': '8600 1234 5678 9012', 'card_owner': 'TEZ SOT', 'bank_name': 'HUMO', 'card_type': 'humo', 'active': true}]", verbose_name='Bank kartalari (JSON)'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='payment_methods_json',
            field=models.JSONField(default=list, help_text="To'lov usullari JSON formatida. Misol: [{'name': 'HUMO', 'icon': 'credit-card', 'active': true}]", verbose_name="To'lov usullari (JSON)"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, verbose_name="Admin tasdig'ini talab qilish"),
        ),
    ]
