# Generated by Django 5.2.11 on 2026-02-22 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0042_remove_adminpremiumsettings_auto_renew_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(choices=[('elektronika', 'Elektronika'), ('kitob', 'Kitoblar'), ('mebel', 'Mebellar'), ('cheteltovarlar', 'Chet el tovarlari'), ('uyjoyelonlari', 'Uy joy elonlari'), ('onavabollar', 'Onalar va bolalar'), ('avto_elonlari', 'Auto elonlar'), ('uy_jihozlari', 'Uy jihozlari'), ('kiyim', 'Kiyim-kechak'), ('avto', 'Avto ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya')),
                ('mahsulotturi', models.CharField(max_length=100, verbose_name='Mahsulot turi')),
                ('price', models.CharField(max_length=50, verbose_name="Narx (so'm)")),
                ('brand', models.CharField(max_length=100, verbose_name='Brend')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('image', models.ImageField(upload_to='top_products/', verbose_name='Mahsulot rasmi')),
                ('birimg', models.ImageField(blank=True, null=True, upload_to='top_products/', verbose_name='1-rasm')),
                ('ikkiimg', models.ImageField(blank=True, null=True, upload_to='top_products/', verbose_name='2-rasm')),
                ('uchuimg', models.ImageField(blank=True, null=True, upload_to='top_products/', verbose_name='3-rasm')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, verbose_name='Reyting')),
                ('discount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Chegirma')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium mahsulotmi')),
                ('viloyat', models.CharField(blank=True, choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent_vil', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ('fargona', 'Farg‘ona'), ('jizzax', 'Jizzax'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', 'Qoraqalpog‘iston')], max_length=100, null=True, verbose_name='Viloyat')),
                ('tuman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar')),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Aniq manzil')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Admin tasdiqlaganmi')),
                ('rank', models.PositiveIntegerField(default=1, verbose_name="O'rin (1-8)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_products', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': 'TOP Mahsulot',
                'verbose_name_plural': 'TOP Mahsulotlar',
                'ordering': ['rank'],
            },
        ),
    ]
