# Generated by Django 6.0.4 on 2026-05-07 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0043_topproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='bank_cards_json',
        ),
        migrations.RemoveField(
            model_name='adminpremiumsettings',
            name='payment_methods_json',
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='auto_renew_days',
            field=models.PositiveIntegerField(default=30, help_text='Avtomatik uzaytiriladigan kunlar soni', verbose_name='Avtomatik uzaytirish kuni'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_card_number',
            field=models.CharField(blank=True, help_text="To'lov qilish uchun karta raqami", max_length=50, null=True, verbose_name='Bank karta raqami'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_card_owner',
            field=models.CharField(blank=True, help_text='Karta egasining ismi', max_length=100, null=True, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank nomi', max_length=100, null=True, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='payment_methods',
            field=models.TextField(blank=True, default='Bank karta\nClick\nPayme\nUzumbank', help_text='Har bir usul yangi qatorda', null=True, verbose_name="To'lov usullari"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='admin_contact_phone',
            field=models.CharField(default='+998901234567', max_length=20, verbose_name='Admin telefon raqami'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_approve_premium',
            field=models.BooleanField(default=False, help_text='Premium mahsulotlarni avtomatik tasdiqlash', verbose_name='Premiumni avtomatik tasdiqlash'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='auto_renew_premium',
            field=models.BooleanField(default=False, help_text='Premium muddati tugaganda avtomatik uzaytirish', verbose_name='Premiumni avtomatik uzaytirish'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_end_date',
            field=models.DateField(blank=True, help_text='Chegirma tugash sanasi (ixtiyoriy)', null=True, verbose_name='Chegirma tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=10, help_text='Chegirma foizi (%)', validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='has_discount',
            field=models.BooleanField(default=False, help_text='Premium uchun chegirma mavjudmi?', verbose_name='Chegirma yoqilsinmi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_products',
            field=models.PositiveIntegerField(default=5, help_text='1 premium foydalanuvchi uchun max mahsulotlar', verbose_name='Premium mahsulot limiti'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='max_premium_requests_per_user',
            field=models.PositiveIntegerField(default=3, help_text="1 foydalanuvchi oyiga nechta so'rov yuborishi mumkin", verbose_name="Premium so'rovlar limiti"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=3, help_text='Premium tugashidan necha kun oldin ogohlantirish', verbose_name='Ogohlantirish kuni'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Premium obuna muddati kunlarda', verbose_name='Premium muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_fee_amount',
            field=models.DecimalField(decimal_places=2, default=15000.0, help_text='1 ta mahsulotni premium qilish uchun narx', max_digits=10, verbose_name='1 ta mahsulot narxi'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_3months_price',
            field=models.DecimalField(decimal_places=2, default=150000.0, help_text='3 oylik premium narx (90 kun)', max_digits=10, verbose_name='3 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_6months_price',
            field=models.DecimalField(decimal_places=2, default=270000.0, help_text='6 oylik premium narx (180 kun)', max_digits=10, verbose_name='6 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_day_price',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='1 kunlik premium uchun narx', max_digits=10, verbose_name='Kunlik premium narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_month_price',
            field=models.DecimalField(decimal_places=2, default=60000.0, help_text='1 oylik premium narx (30 kun)', max_digits=10, verbose_name='1 oylik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_week_price',
            field=models.DecimalField(decimal_places=2, default=12000.0, help_text='1 haftalik premium narx (7 kun)', max_digits=10, verbose_name='1 haftalik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_per_year_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, help_text='1 yillik premium narx (365 kun)', max_digits=10, verbose_name='1 yillik narx'),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='premium_request_expiry_days',
            field=models.PositiveIntegerField(default=7, help_text="Premium so'rov qancha kunga amal qiladi", verbose_name="Premium so'rov muddati"),
        ),
        migrations.AlterField(
            model_name='adminpremiumsettings',
            name='require_admin_approval',
            field=models.BooleanField(default=True, help_text="Premium so'rovlar admin tasdigini talab qilsinmi?", verbose_name='Admin tasdigini talab qilish'),
        ),
        migrations.DeleteModel(
            name='TopProduct',
        ),
    ]
