# Generated by Django 6.0.4 on 2026-05-10 12:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0044_remove_adminpremiumsettings_bank_cards_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='mahsulot',
            name='fronend_mah_categor_bee027_idx',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='search_keywords',
            field=models.TextField(blank=True, help_text="Qidiruv kalit so'zlari"),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured mahsulot'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='premium_priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='premium_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='fronend_mah_search__e98efb_gin'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['name'], name='fronend_mah_name_3a23e7_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['category'], name='fronend_mah_categor_ebe314_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['aktiv'], name='fronend_mah_aktiv_bbfd69_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['sotilgan'], name='fronend_mah_sotilga_b1264f_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['-popularity_score', '-sana'], name='fronend_mah_popular_f102b3_idx'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query', '-created_at'], name='fronend_sea_query_8a3ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at'], name='fronend_sea_created_ec7824_idx'),
        ),
    ]
