# Generated by Django 6.0.4 on 2026-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0045_searchlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=255, verbose_name='Manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram havolasi')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram havolasi')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook havolasi')),
            ],
        ),
    ]
