# Generated by Django 6.0.4 on 2026-05-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0046_footercontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterContact',
        ),
    ]
