# Generated by Django 4.2 on 2026-05-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0047_delete_footercontact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mahsulot',
            name='fronend_mah_search__e98efb_gin',
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='search_vector',
        ),
    ]
