# Generated by Django 4.2 on 2026-05-31 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0048_fix_postgresql_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SotibOlish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('narx', models.CharField(max_length=20, verbose_name='Narx')),
                ('jami_narx', models.CharField(max_length=20, verbose_name='Jami narx')),
                ('status', models.CharField(choices=[('yangi', 'Yangi buyurtma'), ('qabul_qilindi', 'Sotuvchi qabul qildi'), ('yuborildi', "Jo'natildi"), ('yetkazildi', 'Yetkazildi'), ('bajarildi', 'Bajarildi'), ('bekor_qilindi', 'Bekor qilindi')], default='yangi', max_length=20, verbose_name='Holati')),
                ('xaridor_ism', models.CharField(blank=True, max_length=255, verbose_name='Xaridor ismi')),
                ('xaridor_telefon', models.CharField(blank=True, max_length=20, verbose_name='Xaridor telefoni')),
                ('xaridor_manzil', models.TextField(blank=True, verbose_name='Yetkazib berish manzili')),
                ('xaridor_izoh', models.TextField(blank=True, verbose_name='Buyurtma izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('read_by_seller', models.BooleanField(default=False, verbose_name="Sotuvchi ko'rganmi")),
                ('read_by_admin', models.BooleanField(default=False, verbose_name="Admin ko'rganmi")),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotib_olishlar', to='fronend.mahsulot', verbose_name='Mahsulot')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotilgan_mahsulotlarim', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotib_olganlarim', to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Sotib olish',
                'verbose_name_plural': 'Sotib olishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sotibolish',
            index=models.Index(fields=['xaridor', 'status'], name='fronend_sot_xaridor_ffb620_idx'),
        ),
        migrations.AddIndex(
            model_name='sotibolish',
            index=models.Index(fields=['sotuvchi', 'status'], name='fronend_sot_sotuvch_b6aca3_idx'),
        ),
        migrations.AddIndex(
            model_name='sotibolish',
            index=models.Index(fields=['status', 'created_at'], name='fronend_sot_status_34c02d_idx'),
        ),
    ]
