# Generated by Django 4.2 on 2026-05-31 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fronend', '0049_sotibolish_sotibolish_fronend_sot_xaridor_ffb620_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlangan'), ('aktiv', 'Aktiv'), ('tugadi', 'Tugagan'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Holati')),
                ('days', models.PositiveIntegerField(default=7, verbose_name='Necha kun')),
                ('price', models.DecimalField(decimal_places=2, default=20000.0, max_digits=10, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin izohi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_purchases', to='fronend.mahsulot', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Featured xarid',
                'verbose_name_plural': 'Featured xaridlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner sarlavhasi')),
                ('image', models.ImageField(upload_to='banner_purchases/', verbose_name='Banner rasmi')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop/Notebook'), ('mobile', 'Mobile/Tablet')], default='desktop', max_length=10, verbose_name='Qurilma turi')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlangan'), ('aktiv', 'Aktiv'), ('tugadi', 'Tugagan'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Holati')),
                ('days', models.PositiveIntegerField(default=30, verbose_name='Necha kun')),
                ('price', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Banner xaridi',
                'verbose_name_plural': 'Banner xaridlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
