# Generated by Django 4.2 on 2026-05-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0050_featuredpurchase_bannerpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='banner_price_per_day',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Banner reklama uchun 1 kunlik narx', max_digits=10, verbose_name='Banner narxi (1 kun)'),
        ),
        migrations.AddField(
            model_name='adminpremiumsettings',
            name='featured_price_per_day',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Top/Featured mahsulot uchun 1 kunlik narx', max_digits=10, verbose_name='Top mahsulot narxi (1 kun)'),
        ),
    ]
