# Generated by Django 4.2 on 2026-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0051_adminpremiumsettings_banner_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpurchase',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="To'lov cheki"),
        ),
        migrations.AddField(
            model_name='bannerpurchase',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='featuredpurchase',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="To'lov cheki"),
        ),
        migrations.AddField(
            model_name='featuredpurchase',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
    ]
