# Generated by Django 4.2 on 2026-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0052_add_payment_proof_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminpremiumsettings',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='single_admin_premium_settings'),
        ),
    ]
