# Generated by Django 5.2.15 on 2026-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0054_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='miqdor',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni (zaxiradagi)'),
        ),
    ]
