# Generated by Django 5.2.15 on 2026-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0055_add_miqdor_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotibolish',
            name='bekor_qilish_sababi',
            field=models.TextField(blank=True, verbose_name='Bekor qilish sababi'),
        ),
    ]
