# Generated by Django 5.2.15 on 2026-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0056_add_bekor_qilish_sababi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BekorQilishSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=300, verbose_name='Sabab matni')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Bekor qilish sababi',
                'verbose_name_plural': 'Bekor qilish sabablari',
                'ordering': ['tartib'],
            },
        ),
    ]
