# Generated by Django 5.2.15 on 2026-06-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0057_add_bekor_qilish_sababi_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/', verbose_name='Video'),
        ),
    ]
