# Generated by Django 5.2.15 on 2026-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0059_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('profile', 'Profil sahifasi'), ('home', 'Bosh sahifa')], default='profile', max_length=20, verbose_name='Sahifa')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Kichik matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_banners/', verbose_name='Banner rasmi')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Sahifa banneri',
                'verbose_name_plural': 'Sahifa bannerlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
