# Generated by Django 5.2.15 on 2026-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0060_pagebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpurchase',
            name='extended_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Uzaytirishlar soni'),
        ),
        migrations.AddField(
            model_name='bannerpurchase',
            name='notified_1day',
            field=models.BooleanField(default=False, verbose_name='1 kun qoldi xabari yuborilgan'),
        ),
        migrations.AddField(
            model_name='bannerpurchase',
            name='notified_1hour',
            field=models.BooleanField(default=False, verbose_name='1 soat qoldi xabari yuborilgan'),
        ),
        migrations.AddField(
            model_name='bannerpurchase',
            name='notified_2days',
            field=models.BooleanField(default=False, verbose_name='2 kun qoldi xabari yuborilgan'),
        ),
    ]
