# Generated by Django 5.2.4 on 2026-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_bio_profile_instagram_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Foydalanuvchi shartlariga rozimi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rozilik sanasi'),
        ),
    ]
