# Generated by Django 5.2.15 on 2026-06-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_profile_image_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Bildirishnomalar yoqilganmi'),
        ),
    ]
